# Generated by Django 4.2.5 on 2023-09-22 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_remove_post_likes_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="edited",
        ),
    ]
