# Generated by Django 4.2.5 on 2023-10-03 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0009_remove_userprofile_email_and_more"),
        ("posts", "0003_remove_post_edited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="user_profile.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="user_profile.userprofile",
            ),
        ),
    ]
