# Generated by Django 4.2.6 on 2023-10-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_comments_author_alter_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_publish",
            field=models.BooleanField(default=True),
        ),
    ]
