version: "3.1"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"

    env_file:
      - .env

    depends_on:
      - db



  db:
    image: postgres:15.4-alpine3.18
    ports:
      - "5432:5432"
    restart: always
#        volumes:
#          - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env