# Generated by Django 4.2.5 on 2023-09-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0004_userprofile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="username",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
