# Generated by Django 4.2.5 on 2023-09-26 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_profile", "0006_alter_userprofile_followers_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="follower", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
