# Generated by Django 4.2.5 on 2023-09-28 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0008_userprofile_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_name",
        ),
    ]
